### ISSUE TITLE
Cannot connect to internet

### ISSUE THREAD

**Issue by SenshiSoup** [Potato-Development/not-so-securly#1]
Works perfectly, aside from the fact that it cannot connect to internet when trying to search something.

**Comment by MysteryFlask** [comment]
I concur with this gentleman.

**Comment by edamame-maru** [comment]
We apologize for the inconvenience you experienced with the internet connectivity issue. Our team is dedicated to resolving this issue promptly to ensure a seamless experience for all our users. Thank you for bringing this to our attention, and we appreciate your feedback as it helps us improve our services.
